
# if using pure (only) - uncomment following two lines:
# source ~/dotfiles/zsh/pure
# return

export PATH=~/bin:/usr/local/bin/:/usr/local/sbin:/usr/local/share/npm/bin:$PATH
source ~/dotfiles/zsh/zshrc.antigen
setopt no_cdable_vars
export EDITOR=vim

[[ -f ~/.aliases ]] && . ~/.aliases
[[ -f ~/.zsh_userrc ]] && . ~/.zsh_userrc
