
# if using pure (only) - uncomment following two lines:
# source ~/dotfiles/zsh/pure
# return

source ~/dotfiles/zsh/zshrc.antigen
setopt no_cdable_vars
export EDITOR=vim
export PATH=~/bin:/usr/local/share/npm/bin:$PATH

[[ -f ~/.aliases ]] && . ~/.aliases
[[ -f ~/.zsh_userrc ]] && . ~/.zsh_userrc
