
# if using pure (only) - uncomment following two lines:
# source ~/dotfiles/zsh/pure.zsh
# return

source ~/dotfiles/zsh/zshrc.antigen
setopt no_cdable_vars
alias cp='nocorrect cp'
export EDITOR=vim
export PATH=~/bin:/usr/local/share/npm/bin:$PATH
[[ -f ~/.zsh_userrc ]] && . ~/.zsh_userrc
